# Generated by Django 5.1.4 on 2025-01-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
