# Generated by Django 5.1.4 on 2025-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_labeling_task'),
        ('tasks', '0003_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(through='labels.Labeling', to='labels.label'),
        ),
    ]
