name: Tests and linter

on:
  - push
  - pull_request

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install requirements
        run: |
          uv sync
      - name: Apply migrations
        run: |
          uv run python manage.py migrate
      - name: Run linter
        run: |
          uv run ruff check .
      - name: Run tests and coverage
        run: |
          uv run coverage run manage.py test task_manager
          uv run coverage xml -o coverage.xml
      - name: Upload coverage to CodeClimate
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: uv run coverage xml -o coverage.xml